tags/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^$', views.tags, name='tags'),
    url(r'^(?P<tag_name>.*?)/$', views.tag, name='tag'),
]

tags/models.py
# -*- coding: utf-8 -*-

from django.db import models
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes.fields import GenericForeignKey
from django.urls import reverse
from django.db.models import Count


class Tag(models.Model):
    name = models.CharField(max_length=100, unique=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('tag', kwargs={'tag_name': self.name})


class TagManager(models.Manager):
    def top_tags(self, max=15):
        top = self.model.objects.values(
                  'tag__name').annotate(
                      score=Count('tag')).order_by('-score')[:max]

        return top


class TagItem(models.Model):
    class Meta:
        unique_together = ('tag', 'content_type', 'object_id')

    tag = models.ForeignKey('Tag', on_delete=models.CASCADE)
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField(db_index=True)
    obj = GenericForeignKey('content_type', 'object_id')

    objects = TagManager()

tags/forms.py
# -*- coding: utf-8 -*-
from django import forms
from django.contrib.contenttypes.models import ContentType

from .models import Tag, TagItem


def set_tags(obj, tags):
    dynamic_type = ContentType.objects.get_for_model(obj)

    TagItem.objects.filter(
        content_type=dynamic_type,
        object_id=obj.id,
        ).delete()

    tags = tags.split(' ')
    for tag_name in tags:
        tag, is_new = Tag.objects.get_or_create(name=tag_name.strip())

        TagItem.objects.get_or_create(
            tag=tag,
            content_type=dynamic_type,
            object_id=obj.id,
        )


def get_tags(obj):
    dynamic_type = ContentType.objects.get_for_model(obj)

    tags = TagItem.objects.filter(
        content_type=dynamic_type,
        object_id=obj.id,
        )

    return ' '.join([item.tag.name for item in tags])


class FormTags(forms.ModelForm):

    tags = forms.CharField(max_length=100,
                           required=False,
                           help_text="Digite as palavras-chave separadas por um espaço em branco")

    def __init__(self, *args, **kwargs):
        super(FormTags, self).__init__(*args, **kwargs)

        if self.instance.id:
            self.initial['tags'] = get_tags(self.instance)

tags/views.py
from django.shortcuts import render, get_object_or_404

from .models import Tag


def tags(request):
    list = Tag.objects.all()
    return render(request,
                  'tags/tags.html',
                  locals())


def tag(request, tag_name):
    tag = get_object_or_404(Tag, name=tag_name)
    return render(request,
                  'tags/tag.html',
                  locals())

tags/templates/tags/base.html
{% block content %}
{% endblock %}

tags/templates/tags/show_tags.html
{% load tags_tags %}

<p>
{% for tag in object|get_tags %}
{% if forloop.first %}Tags: {% endif %}
<a href="{{ tag.get_absolute_url }}">{{ tag }}</a>{% if not forloop.last %}, {% endif %}
{% endfor %}
</p>

tags/templates/tags/tag.html
{% extends "base.html" %}
{% block content %}
<h1>Tag "{{ tag.name }}"</h1>

<ul>
    {% for item in tag.tagitem_set.all %}
    <li><a href="{{ item.obj.get_absolute_url }}">{{ item.obj }}</a></li>
    {% endfor %}
</ul>
{% endblock %}

tags/templates/tags/tags.html
{% extends "base.html" %}
{% block content %}
<h1>Tags</h1>
<ul>
    {% for tag in list %}
    <li><a href="{{ tag.get_absolute_url }}">{{ tag }}</a></li>
    {% endfor %}
</ul>
{% endblock %}